volumes:
  bias-data:
services:
  db:
    container_name: bias-db
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 1gb
    volumes:
      - bias-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: biasgg
      POSTGRES_DB: biasgg-dev
      POSTGRES_PASSWORD: Passw0rd! 
    ports:
      - 5432:5432

  pgadmin:
    container_name: bias-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bias.gg
      PGADMIN_DEFAULT_PASSWORD: Passw0rd!
    ports:
      - 5050:80
