name: Build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: 1.2.15

            - name: Install dependencies
              run: |
                npm install

            - name: Build
              run: |
                bun run build

