name: Format

on:
    push:
        branches: ["*"]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    format:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup bun
              uses: oven-sh/setup-bun@v2

            - name: Install yarn
              run: bun install -g yarn

            - name: Install packages
              run: yarn

            - name: Check formatting
              run: yarn exec biome format


